version: "3.9"

services:
  backend:
    env_file: ./backend/.env
    container_name: "app_backend"
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    environment:
      - DB_HOST=db
    networks:
      - mynetwork
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
    container_name: "app_frontend"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    networks:
      - mynetwork
    depends_on:
      - backend

  database:
    container_name: "app_database"
    image: postgres:16.0-alpine3.18
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgress
      - POSTGRES_USER=postgress
      - POSTGRES_PASSWORD=postgress
    networks:
      - mynetwork

networks:
  mynetwork:
    name: "app_network"
